Mon, 17 Jul 2017 20:14:09 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:14:13 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:14:15 server.py[line:100] INFO New Connection Address is ('127.0.0.1', 2697)
Mon, 17 Jul 2017 20:14:15 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:14:18 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:14:21 server.py[line:143] WARNING Error at handle_mew_conn
Mon, 17 Jul 2017 20:14:21 server.py[line:144] WARNING Address is ('127.0.0.1', 2697).
Mon, 17 Jul 2017 20:14:21 server.py[line:145] WARNING Traceback (most recent call last):
  File "src\server.py", line 115, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 337, in recv
    self._wait(self._read_event)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 899, in get
    return self.hub.switch()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
socket.timeout: timed out

Mon, 17 Jul 2017 20:14:22 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:14:25 server.py[line:100] INFO New Connection Address is ('127.0.0.1', 2706)
Mon, 17 Jul 2017 20:14:25 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:14:26 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:14:30 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:14:35 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:14:35 server.py[line:139] INFO Connection of ('127.0.0.1', 2706) Closed!
Mon, 17 Jul 2017 20:14:39 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:15:40 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:15:45 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:15:46 server.py[line:100] INFO New Connection Address is ('127.0.0.1', 2760)
Mon, 17 Jul 2017 20:15:46 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:15:49 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:15:53 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:15:57 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:01 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:06 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:10 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:14 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:18 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:22 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:26 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:26 server.py[line:139] INFO Connection of ('127.0.0.1', 2760) Closed!
Mon, 17 Jul 2017 20:16:29 server.py[line:76] WARNING Error at renew_obj
Mon, 17 Jul 2017 20:16:30 server.py[line:77] WARNING Traceback (most recent call last):
  File "src\server.py", line 71, in renew_obj
    self.rm.renew_status()
  File "E:\jsfk-new\risk-control-server\src\riskmanage.py", line 145, in renew_status
    self.renew_stock_status()
  File "E:\jsfk-new\risk-control-server\src\riskmanage.py", line 87, in renew_stock_status
    temp = data[loc1&loc2]
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2053, in __getitem__
    return self._getitem_array(key)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2095, in _getitem_array
    return self.take(indexer, axis=0, convert=False)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1669, in take
    convert=True, verify=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3964, in take
    axis=axis, allow_dups=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3850, in reindex_indexer
    for blk in self.blocks]
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3850, in <listcomp>
    for blk in self.blocks]
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 1022, in take_nd
    allow_fill=True, fill_value=fill_value)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 1041, in take_nd
    if is_categorical(arr):
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\types\common.py", line 66, in is_categorical
    return isinstance(array, ABCCategorical) or is_categorical_dtype(array)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\types\generic.py", line 9, in _check
    return getattr(inst, attr, '_typ') in comp
KeyboardInterrupt

Mon, 17 Jul 2017 20:16:30 server.py[line:78] WARNING file may not be available now
Mon, 17 Jul 2017 20:16:34 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:38 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:42 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:46 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:50 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:54 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:16:59 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:03 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:07 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:11 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:15 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:20 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:24 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:28 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:17:32 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:22:59 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:22:59 server.py[line:100] INFO New Connection Address is ('127.0.0.1', 2984)
Mon, 17 Jul 2017 20:22:59 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:23:03 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:23:07 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:23:12 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:23:16 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:23:20 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:23:24 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:23:24 server.py[line:139] INFO Connection of ('127.0.0.1', 2984) Closed!
Mon, 17 Jul 2017 20:23:27 server.py[line:76] WARNING Error at renew_obj
Mon, 17 Jul 2017 20:23:27 server.py[line:77] WARNING Traceback (most recent call last):
  File "src\server.py", line 72, in renew_obj
    self.new_data = self.rm.get_current_status2()
  File "E:\jsfk-new\risk-control-server\src\riskmanage.py", line 191, in get_current_status2
    res = self.total(res)
  File "E:\jsfk-new\risk-control-server\src\riskmanage.py", line 292, in total
    loc1 = data['Code']==code
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 855, in wrapper
    res = na_op(values, other)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 759, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 739, in _comp_method_OBJECT_ARRAY
    result = lib.scalar_compare(x, y, op)
  File "pandas\lib.pyx", line 773, in pandas.lib.scalar_compare (pandas\lib.c:13982)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 946, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 885, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1241, in find_spec
  File "<frozen importlib._bootstrap_external>", line 82, in _path_stat
KeyboardInterrupt

Mon, 17 Jul 2017 20:23:27 server.py[line:78] WARNING file may not be available now
Mon, 17 Jul 2017 20:24:32 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:24:36 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:24:43 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:24:47 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:24:51 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:24:55 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:25:00 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:25:03 server.py[line:100] INFO New Connection Address is ('127.0.0.1', 3185)
Mon, 17 Jul 2017 20:25:03 server.py[line:96] INFO Waiting for connection.
Mon, 17 Jul 2017 20:25:04 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:25:08 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:25:12 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:25:16 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:25:17 server.py[line:139] INFO Connection of ('127.0.0.1', 3185) Closed!
Mon, 17 Jul 2017 20:25:20 server.py[line:73] INFO Data Recieved.
Mon, 17 Jul 2017 20:25:24 server.py[line:73] INFO Data Recieved.
