2021/11/04 23:53:07 PM - DEBUG[thread_pool_module/start(19)] - thread start
2021/11/04 23:53:08 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数10
2021/11/04 23:53:09 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数9
2021/11/04 23:53:10 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数8
2021/11/04 23:53:11 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数7
2021/11/04 23:53:12 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数6
2021/11/04 23:53:13 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数5
2021/11/04 23:53:14 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数4
2021/11/04 23:53:15 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数3
2021/11/04 23:53:16 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数2
2021/11/04 23:53:17 PM - ERROR[simpleServer/connect(58)] - 无法连接服务器，尝试重连。。。剩余重连次数1
2021/11/04 23:53:18 PM - ERROR[simpleServer/connect(61)] - 无法连接服务器，请检查服务器状态
2021/11/04 23:53:18 PM - ERROR[simpleServer/<module>(152)] - 
Traceback (most recent call last):
  File "simpleServer.py", line 50, in connect
    self.netstream.connect(self.config.ip, self.config.port)
  File "E:\fengkong\Worker\network\netStream.py", line 94, in connect
    raise socket.error
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simpleServer.py", line 150, in <module>
    TimerManager.scheduler()
  File "E:\fengkong\Worker\common_server\timer.py", line 88, in scheduler
    repeated = call.call()
  File "E:\fengkong\Worker\common_server\timer.py", line 47, in call
    self._target(*self._args, **self._kwargs)
  File "simpleServer.py", line 63, in connect
    sys.exit()
SystemExit
